[build]
command = "npm run build"
functions = "out_functions"
publish = "out_publish"

[dev]
framework = "#static"
functions = "out_functions"
publish = "out_publish"

[[plugins]]
package = "netlify-plugin-cache-nextjs"

[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
package = "netlify-plugin-minify-html"

[[plugins]]
package = "@netlify/plugin-sitemap"
[plugins.inputs]
buildDir = "out_publish"
prettyURLs = true
trailingSlash = true

[[redirects]]
from = "/"
status = 200
to = "/en.html"

[[redirects]]
from = "/404"
status = 200
to = "/en/404.html"

[[redirects]]
from = "/en/*"
status = 404
to = "/en/404.html"

[[redirects]]
from = "/nl/*"
status = 404
to = "/nl/404.html"

[[redirects]]
from = "/*"
status = 404
to = "/en/404.html"
